// examples/vue/src/App.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, ref } from 'vue'

const seed = ref(0)
const autopilot = ref(false)
let autopilotTimer: number | undefined

const cards = computed(() => {
  return Array.from({ length: 16 }, (_, index) => {
    const rate = Math.abs(Math.sin((index + 1 + seed.value) * 0.37)) * 100
    const drift = Math.cos((seed.value + index) * 0.29)
    return {
      id: index + 1,
      title: `Signal ${index + 1}`,
      rate: rate.toFixed(1),
      drift: drift.toFixed(3),
    }
  })
})

function shuffle() {
  seed.value += 1
}

function burst() {
  let ticks = 0
  const timer = window.setInterval(() => {
    seed.value += 1
    ticks += 1
    if (ticks >= 18)
      window.clearInterval(timer)
  }, 75)
}

function toggleAutopilot() {
  autopilot.value = !autopilot.value

  if (!autopilot.value) {
    if (autopilotTimer != null)
      window.clearInterval(autopilotTimer)
    autopilotTimer = undefined
    return
  }

  autopilotTimer = window.setInterval(() => {
    seed.value += 1
  }, 240)
}

onBeforeUnmount(() => {
  if (autopilotTimer != null)
    window.clearInterval(autopilotTimer)
})
</script>

<template>
  <main class="page">
    <header class="hero">
      <p class="eyebrow">Vue example</p>
      <h1>Watch reactive updates ripple</h1>
      <p class="copy">
        This view leans on computed state so Vue produces a steady stream of DOM updates for
        <strong>Vite Scan</strong> to highlight.
      </p>
    </header>

    <section class="toolbar">
      <button type="button" @click="shuffle">
        Shuffle signals
      </button>
      <button type="button" @click="burst">
        Burst updates
      </button>
      <button type="button" :class="['secondary', { active: autopilot }]" @click="toggleAutopilot">
        {{ autopilot ? 'Stop autopilot' : 'Start autopilot' }}
      </button>
    </section>

    <section class="stack">
      <article v-for="card in cards" :key="card.id" class="panel">
        <span class="label">{{ card.title }}</span>
        <strong>{{ card.rate }}%</strong>
        <p>Drift {{ card.drift }}</p>
      </article>
    </section>
  </main>
</template>

// examples/svelte/src/App.svelte
<script lang="ts">
  let seed = 0
  let autopilot = false
  let autopilotTimer: number | undefined

  $: cards = Array.from({ length: 20 }, (_, index) => {
    const tempo = Math.abs(Math.sin((index + 1 + seed) * 0.31)) * 100
    const delta = Math.cos((seed + index) * 0.41)
    return {
      id: index + 1,
      title: `Block ${index + 1}`,
      tempo: tempo.toFixed(1),
      delta: delta.toFixed(3),
    }
  })

  function shuffle() {
    seed += 1
  }

  function burst() {
    let ticks = 0
    const timer = window.setInterval(() => {
      seed += 1
      ticks += 1
      if (ticks >= 22)
        window.clearInterval(timer)
    }, 65)
  }

  function toggleAutopilot() {
    autopilot = !autopilot

    if (!autopilot) {
      if (autopilotTimer != null)
        window.clearInterval(autopilotTimer)
      autopilotTimer = undefined
      return
    }

    autopilotTimer = window.setInterval(() => {
      seed += 1
    }, 210)
  }
</script>

<svelte:head>
  <title>vite-scan Svelte Example</title>
</svelte:head>

<svelte:window
  on:beforeunload={() => {
    if (autopilotTimer != null)
      window.clearInterval(autopilotTimer)
  }}
/>

<main class="page">
  <header class="hero">
    <p class="eyebrow">Svelte example</p>
    <h1>Stress test fine-grained updates</h1>
    <p class="copy">
      Trigger reactive changes and inspect which DOM islands churn under <strong>Vite Scan</strong>.
    </p>
  </header>

  <section class="toolbar">
    <button type="button" on:click={shuffle}>Shuffle blocks</button>
    <button type="button" on:click={burst}>Burst updates</button>
    <button type="button" class:active={autopilot} class="secondary" on:click={toggleAutopilot}>
      {autopilot ? 'Stop autopilot' : 'Start autopilot'}
    </button>
  </section>

  <section class="grid">
    {#each cards as card (card.id)}
      <article class="tile">
        <span class="badge">{card.title}</span>
        <strong>{card.tempo}%</strong>
        <p>Delta {card.delta}</p>
      </article>
    {/each}
  </section>
</main>
