// examples/react/src/TextPreview.tsx
import { useState } from 'react'

export function TextPreview() {
  const [text, setText] = useState('')

  return (
    <section className="input-section">
      <div className="input-wrapper">
        <input type="text" placeholder="Type here to generate more updates" className="input" value={text} onChange={e => setText(e.target.value)} />
      </div>
      <output className={`input-value${text ? '' : ' placeholder'}`}>
        {text || 'Your text will appear here...'}
      </output>
    </section>
  )
}

// examples/svelte/src/TextPreview.svelte
<script lang="ts">
  let text = ''
</script>

<section class="input-section">
  <div class="input-wrapper">
    <input type="text" placeholder="Type here to generate more updates" class="input" bind:value={text} />
  </div>
  <output class="input-value" class:placeholder={!text}>
    {text || 'Your text will appear here...'}
  </output>
</section>
